const state = {
    activeMessengers: [],
    folders: [],
    activeTabId: null,
    unreadCounts: {},
    rawUnreadCounts: {},
    mutedMessengers: {},
    globalMuteAll: false,
    contextTargetId: null,
    contextTargetFolderId: null,
    editMode: null,
    selectedFolderIcon: 'folder',
    soundTargetId: null,
    activeFolderPanelId: null,
    dragSrcId: null,
    dragSrcType: null,
    modalPage: 0,
    modalFiltered: [],
    menuCollapsed: false,
    appZoomLevel: 0,
    tabZoomLevel: 1.0,
    wvContextParams: {},
    changeIconTargetId: null,
    changeIconNewSrc: null,
    tooltipTimeout: null,
    pinNewVal: '',
    pinConfirmVal: '',
    pinActive: null,
    disableVal: '',
    messengerNotifyState: {},
    webviewWatchBound: new Set(),
    siteNotificationState: {},
    unreadStabilizeTimers: {}
}

module.exports = state